config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :articles do
    resources :comments
  end
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :text, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  http_basic_authenticate_with name: "user", password: "article", except: [:index, :show]

  def new
    @article = Article.new
  end

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(allowed_article_params)
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(allowed_article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private
    def allowed_article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with name: "user", password: "comment", only: :destroy

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(allowed_comment_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private
    def allowed_comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>

  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
      </h3>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<% if @article.errors.any? %>
  <p><%= link_to 'Refresh form', edit_article_path(@article) %></p>
<% end %>
<%= link_to 'Home', articles_path %>

app/views/articles/index.html.erb
<h1>All articles - <%= @articles.count %> total</h1>

<%= link_to 'New article', new_article_path %>

<table border="0" cellpadding="10" cellspacing="10">
  <tr>
    <th>Id</th>
    <th>Title</th>
    <th>Text</th>
    <th>Has comments</th>
    <th colspan="3">&nbsp;</th>
  </tr>

  <% @articles.each do |article| %>
    <tr>
      <td><%= article.id %></td>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td align="center"><%= article.comments.count %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
      <td><%= link_to 'Edit', edit_article_path(article) %></td>
      <td><%= link_to 'Delete', article_path(article), method: :delete, data: {
        confirm: "Are you sure you want to delete article no. #{article.id}?"
      } %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<% if @article.errors.any? %>
  <p><%= link_to 'Refresh form', new_article_path %></p>
<% end %>
<%= link_to 'Home', articles_path %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>

<% if @article.comments.any? %>
  <hr />
  <h3>Comments (<%= @article.comments.count %> total):</h3>
  <%= render @article.comments %>
<% end %>

<hr />
<%= render 'comments/form' %>
<hr />

<p><%= link_to 'Edit', edit_article_path(@article) %></p>
<p><%= link_to 'Delete', article_path(@article), method: :delete, data: {
  confirm: "Are you sure you want to delete article no. #{@article.id}?"
} %></p>
<%= link_to 'Home', articles_path %>

app/views/comments/_comment.html.erb
<p>
  <strong>Commenter: </strong><%= comment.commenter %>
  <br />
  <strong>Comment: </strong><%= comment.body %>
  <%= link_to 'Delete', article_comment_path(@article, comment), method: :delete, data: {
    confirm: "Are you sure you want to delete the comment by #{comment.commenter}?"
  } %>
</p>

app/views/comments/_form.html.erb
<h3>Add a comment:</h3>
<%= form_with model: [ @article, Comment.new ], local: true do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsHello514</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>